### ISSUE TITLE
HiChIP QC error

### ISSUE THREAD

**Issue by cpadillla1331** [dovetail-genomics/dovetail_tools#12]
@dtg-jayghurye 
Traceback (most recent call last):
  File "/home/ubuntu/omni-c_qc/hichip_qc/./plot_chip_enrichment.py", line 67, in <module>
    plt.xticks(ticks=x_ticks, labels=x_labels)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1543, in xticks
    ax = gca()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 935, in gca
    return gcf().gca(**kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 578, in gcf
    return figure()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 525, in figure
    **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3218, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 1008, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/home/ubuntu/miniconda3/envs/dovetail/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:10.0"
Traceback (most recent call last):
  File "/home/ubuntu/omni-c_qc/hichip_qc/./count.py", line 4, in <module>
    import pysam
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /home/ubuntu/miniconda3/envs/dovetail/bin/../lib/libssl.so.1.1: symbol EVP_idea_cbc version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference

**Comment by dtg-jayghurye** [comment]
Was your conda environment built successfully?

**Comment by cpadillla1331** [comment]
There was a small hiccup at the start:

c_qc/conda/environment.yaml' file not found

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

$ conda init <SHELL_NAME>
Currently supported shells are:

bash
fish
tcsh
xonsh
zsh
powershell
See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Its either a typo in the code or in the file name because its looking for a file ending in ".yaml" but the file in the environment is ".yml". I changed the file end with ".yaml" and it worked

**Comment by cpadillla1331** [comment]
WHen I'm in the conda directoy and run ./create.sh I get


CondaValueError: prefix already exists: /home/ubuntu/miniconda3/envs/dovetail


CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

**Comment by cpadillla1331** [comment]
I have to run:
conda activate dovetail
