### ISSUE TITLE
index error in the pairtools split

### ISSUE THREAD

**Issue by Luma-1994** [dovetail-genomics/dovetail_tools#21]
Hi, 
I was trying to submit a job with this script:
#!/bin/sh
#SBATCH -J pairtools
#SBATCH -p l_long
#SBATCH --qos=ll
#SBATCH --mem=100G
#SBATCH --time=96:00:00
#SBATCH --ntasks=1
#SBATCH -c 8
#SBATCH --output=pairtools-split.o
#SBATCH --error=pairtools-split.e
pairtools split \
        --nproc-in 8 --nproc-out 8 \
        --output-pairs GM12878_Omni-C.PT.pairs.gz  \
        --output-sam GM12878-split.bam \
~/script/GM12878_dedup.pairsam

and we have this error:
Traceback (most recent call last):
  File "/lustre/home/lusrour80/miniconda3/bin/pairtools", line 11, in <module>
    sys.exit(cli())
  File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/pairtools/__init__.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/pairtools/pairtools_split.py", line 46, in split
    split_py(pairsam_path, output_pairs, output_sam, **kwargs)
  File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/pairtools/pairtools_split.py", line 109, in split_py
    sam2 = cols.pop(sam2col)
IndexError: pop index out of range
It did work before when I tried to use the output from the sort step in omni-c_qc.bash
what can be the reason that it is not working on the dedup output file?

**Comment by Luma-1994** [comment]
> Hi,
> I was trying to submit a job with this script:
> #!/bin/sh
> #SBATCH -J pairtools
> #SBATCH -p l_long
> #SBATCH --qos=ll
> #SBATCH --mem=100G
> #SBATCH --time=96:00:00
> #SBATCH --ntasks=1
> #SBATCH -c 8
> #SBATCH --output=pairtools-split.o
> #SBATCH --error=pairtools-split.e
> pairtools split
> --nproc-in 8 --nproc-out 8
> --output-pairs GM12878_Omni-C.PT.pairs.gz
> --output-sam GM12878-split.bam
> ~/script/GM12878_dedup.pairsam
> 
> and we have this error:
> Traceback (most recent call last):
> File "/lustre/home/lusrour80/miniconda3/bin/pairtools", line 11, in
> sys.exit(cli())
> File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in **call**
> return self.main(*args, **kwargs)
> File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
> rv = self.invoke(ctx)
> File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
> return callback(*args, **kwargs)
> File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/pairtools/**init**.py", line 113, in wrapper
> return func(*args, **kwargs)
> File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/pairtools/pairtools_split.py", line 46, in split
> split_py(pairsam_path, output_pairs, output_sam, **kwargs)
> File "/lustre/home/lusrour80/miniconda3/lib/python3.8/site-packages/pairtools/pairtools_split.py", line 109, in split_py
> sam2 = cols.pop(sam2col)
> IndexError: pop index out of range
> It did work before when I tried to use the output from the sort step in omni-c_qc.bash
> what can be the reason that it is not working on the dedup output file?
